training_text: './data/x_train_split.txt'
training_labels: './data/y_train_split.txt'
testing_text: './data/x_test_split.txt'
testing_labels: './data/y_test_split.txt'
validation_text: './data/x_valid_split.txt'
validation_labels: './data/y_valid_split.txt'
taiga_train_path: './data/taiga_train/'
taiga_valid_path: './data/taiga_valid/'
taiga_test_path: './data/taiga_test/'

batch_size : 128
log_frequency : 100
dropout_p : 0.0
split_paragraphs : True
eval_frequency : 500
epochs : 10
embedding_dim : 64
hidden_dim : 128
max_chars : 1000
learning_rate: 0.001
bidirectional: False